source 'https://rubygems.org'

gem 'builder'
gem 'image_optim_pack'
gem 'middleman'
gem 'middleman-autoprefixer'
gem 'middleman-favicon-maker'
gem 'middleman-imageoptim'
gem 'middleman-minify-html'
gem 'mini_racer'
gem 'bootstrap', '4.0.0'
